/**
 * This is a file containing the different secret keys the server will use, including for authentication.
 * SESSION_SECRET: a random string of characters used internally to keep user sessions. This can be generated by yourself, just generate a random, long string of characters
 *
 * Google:
 *  GOOGLE_CLIENT_ID: The client ID used for the Google API
 *  GOOGLE_CLIENT_SECRET: The client secret used for the Google API
 */

export const SESSION_SECRET = 'AAAAAAAABBBBBBBBBBBBBCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEFFFFFFFFFFFFF'

export const GOOGLE = {
    GOOGLE_CLIENT_ID: 'AAAAAAAAAAAAA-BBBBBBBBBBBBBBBBBB.apps.googleusercontent.com',
    GOOGLE_CLIENT_SECRET: 'IUHO99Nibnfiopjhhjf90whfw39'
}

export const LOGIN_INFO = 'user:pass@'

export const JWT_SECRET = 'cAAAAAAAAAAAAAAAAAAAAAAAAAAAA0'